#!/bin/bash 

 # script: setup-tunnel
 # Project: SharedAppVnc
 #
 # Copyright (C) 2005 Grant Wallace, Princeton University. All Rights Reserved.
 #
 #  This is free software; you can redistribute it and/or modify
 #  it under the terms of the GNU General Public License as published by
 #  the Free Software Foundation; either version 2 of the License, or
 #  (at your option) any later version.
 #
 #  This software is distributed in the hope that it will be useful,
 #  but WITHOUT ANY WARRANTY; without even the implied warranty of
 #  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 #  GNU General Public License for more details.
 #
 #  You should have received a copy of the GNU General Public License
 #  along with this software; if not, write to the Free Software
 #  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307,
 #  USA.

if [ $# -eq 0 ]; then
  echo "Usage: $0 -in localPort:commonHost:inTunnelPort -out localPort:commonHost:outTunnelPort [-opts ssh-options]"
  exit 1;
fi

for arg in $*
do
    shift
    if [ $arg = "-in" ]; then
      in=$1
    fi
    if [ $arg = "-out" ]; then
      out=$1
    fi
    if [ $arg = "-opts" ]; then
      sshopts=$1
    fi
done


echo "Setting up tunnels"
if [ $in ]; then
  inLocalPort=`expr "$in" : '\([0-9]*\)'`;
  inHost=`expr "$in" : '[0-9:]*\(.*\):'`;
  inTunnelPort=`expr "$in" : '.*:\(.*\)'`;
  if [ -z $inLocalPort ]; then
    inLocalPort=5500
    #inLocalPort=$inTunnelPort
  fi
  echo "IN: $inLocalPort:$inHost:$inTunnelPort"
  # set up incomming tunnel
  echo ssh $sshopts -g -f -N -R $inTunnelPort:localhost:$inLocalPort $inHost 
  ssh $sshopts -g -f -N -R $inTunnelPort:localhost:$inLocalPort $inHost 

fi

if [ $out ]; then
  outLocalPort=`expr "$out" : '\([0-9]*\)'`;
  outHost=`expr "$out" : '[0-9:]*\(.*\):'`;
  outTunnelPort=`expr "$out" : '.*:\(.*\)'`;
  if [ -z $outLocalPort ]; then
    outLocalPort=$outTunnelPort
  fi
  echo "OUT: $outLocalPort:$outHost:$outTunnelPort"
  # set up outgoing tunnel
  echo ssh $sshopts -g -f -N -L $outLocalPort:localhost:$outTunnelPort $outHost 
  ssh $sshopts -g -f -N -L $outLocalPort:localhost:$outTunnelPort $outHost 

fi






exit 0;
