#!/bin/sh
echo "Check xc/config/cf/host.def for correct configuration."
echo "Hit CTRL+C now, if you've not configured this file."
sleep 5
cd xc
make World
cd ../libvncauth
imake -I../xc/config/cf
make clean
make
make -f Makefile.modules
cd ../xc
make
