//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WinVNC.rc
//
#define ID_HIDE_WIN                     3
#define IDI_WINVNC                      102
#define IDD_PROPERTIES                  102
#define IDR_TRAYMENU                    104
#define IDR_VNCVIEWER_JAR               116
#define IDR_RECFRAME_CLASS              117
#define IDR_SESSIONREC_CLASS            118
#define IDR_AUTHPANEL_CLASS             119
#define IDR_RELOGINPANEL_CLASS          120
#define IDR_SOCKFACTORY_CLASS           121
#define IDR_CLIPBOARDFRAME_CLASS        122
#define IDR_OPTIONSFRAME_CLASS          125
#define IDR_RFBPROTO_CLASS              126
#define IDR_VNCCANVAS_CLASS             127
#define IDR_VNCVIEWER_CLASS             128
#define IDR_BUTTONPANEL_CLASS           129
#define IDD_ABOUT                       131
#define IDB_VNCLOGO                     132
#define IDR_DESCIPHER_CLASS             133
#define IDI_FLASH                       134
#define IDD_OUTGOING_CONN               135
#define IDD_CLIENTS                     135
#define IDD_ACCEPT_CONN                 136
#define IDD_ADVPROPERTIES               137
#define IDI_DISABLED                    138
#define IDR_HTTPCONNSOCKFACTORY_CLASS   139
#define IDR_HTTPCONNSOCK_CLASS          140
#define IDD_SELECT_WIN                  141
#define IDD_SHARED_WINDOWS              141
#define IDD_MODE                        143
#define IDI_UP_ARROW                    145
#define IDI_DOWN_ARROW                  146
#define IDI_UPALL_ARROW                 147
#define IDR_JAVAARCHIVE1                148
#define IDR_SHAREDAPP_VIEWER_JAR        148
#define IDC_CONNECT_BORDER              1003
#define IDC_CONNECT_SOCK                1004
#define IDC_CONNECT_CORBA               1005
#define IDC_PORTNO_LABEL                1006
#define IDC_PASSWORD_LABEL              1007
#define IDC_DISPLAYNO                   1008
#define IDC_PASSWORD                    1009
#define IDC_UPDATE_BORDER               1010
#define IDC_POLL_FULLSCREEN             1011
#define IDC_CONSOLE_ONLY                1012
#define IDC_POLL_FOREGROUND             1013
#define IDC_POLL_UNDER_CURSOR           1014
#define IDC_ONEVENT_ONLY                1015
#define IDC_VNCLOGO                     1016
#define IDC_PORTHTTP                    1017
#define IDC_PORTRFB                     1018
#define IDC_PASSWORD_VIEWONLY_LABEL     1019
#define IDC_PASSWORD_VIEWONLY           1020
#define IDC_DISABLE_INPUTS              1024
#define IDC_APPLY                       1025
#define IDC_PORTNO_AUTO                 1026
#define IDC_HOSTNAME_EDIT               1027
#define IDC_DISABLE_LOCAL_INPUTS        1027
#define IDC_HOSTNAME_STATIC             1028
#define IDC_NOTE_STATIC                 1029
#define IDACCEPT                        1030
#define IDREJECT                        1031
#define IDC_STATIC_TEXT1                1032
#define IDC_ACCEPT_IP                   1033
#define IDC_STATIC_TEXT                 1034
#define IDC_ACCEPT_TIMEOUT              1035
#define IDACCEPT_NOPASS                 1036
#define IDADVANCED                      1037
#define IDC_WIN_LIST                    1037
#define IDQUERY                         1039
#define IDQUERYTIMEOUT                  1042
#define IDREQUIREAUTH                   1043
#define IDQUERYALLOWNOPASS              1044
#define IDONLYLOOPBACK                  1045
#define IDLOGLOTS                       1047
#define IDALLOWLOOPBACK                 1048
#define IDLOG                           1050
#define IDPRIORITY0                     1052
#define IDPRIORITY2                     1053
#define IDPRIORITY1                     1054
#define IDENABLEHTTPD                   1055
#define IDC_SPECDISPLAY                 1071
#define IDC_SPECPORT                    1072
#define IDC_ACTION_REFUSE               1074
#define IDC_ACTION_ACCEPT               1075
#define IDC_REMOVE_WALLPAPER            1076
#define IDC_LOCKSETTING_NOTHING         1077
#define IDC_LOCKSETTING_LOCK            1078
#define IDC_LOCKSETTING_LOGOFF          1079
#define ID_SHARE_WIN                    1080
#define IDC_RADIO_NOSHARING             1084
#define IDC_RADIO_DESKTOP               1085
#define IDC_RADIO3                      1086
#define IDC_RADIO_WINDOWS               1086
#define IDC_MODEGROUP                   1087
#define ID_HIDE_ALL                     1089
#define ID_CONN                         1090
#define IDC_CLIENT_LIST                 1092
#define IDC_DISCONNECT_CLIENT           1094
#define IDC_DISCONNECT_ALL              1095
#define IDC_SHARED_LIST                 1096
#define IDC_START_VIEWER                1097
#define IDC_STOP_VIEWER                 1098
#define IDC_STATIC_VS                   1099
#define IDC_VIEWER_STATUS               1100
#define IDC_DISABLE_INCOMING            1101
#define ID_PROPERTIES                   40001
#define ID_CLOSE                        40002
#define ID_KILLCLIENTS                  40003
#define ID_ABOUT                        40004
#define ID_OUTGOING_CONN                40005
#define ID_DEFAULT_PROPERTIES           40006
#define ID_DISABLE_CONN                 40007
#define ID_SELECT_WIN                   40009
#define ID_TRAY_SHARINGON               40010
#define ID_TRAY_SHAREDESKTOP            40011
#define ID_TRAY_TEST                    40012
#define ID_TEST_TEST1                   40013

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        149
#define _APS_NEXT_COMMAND_VALUE         40014
#define _APS_NEXT_CONTROL_VALUE         1102
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
