#!/bin/sh
echo "Check sharedAppVncServer/xc/config/cf/host.def for correct configuration."
echo "Hit CTRL+C now, if you've not configured this file."
sleep 5
echo "Building SharedAppVnc vnc.so module"
cd sharedAppVncServer/xc
make World
cd ../libvncauth
imake -I../xc/config/cf
make clean
make
make -f Makefile.modules
cd ../xc
make
echo "Building windowshare app"
cd ../../sharedAppVncControl/winshare
make clean
xmkmf
make depend
make windowshare
cd ../javactrl
echo "Building javactrl app"
make clean
make
cd ../../
echo "Copying built binaries to bin"
cp sharedAppVncServer/xc/programs/Xserver/hw/xfree86/vnc/vnc.so bin
cp sharedAppVncServer/xc/programs/Xserver/Xvnc bin
cp sharedAppVncControl/winshare/windowshare bin
cp sharedAppVncControl/javactrl/javactrl.jar bin
cp sharedAppVncControl/javactrl/javactrl bin

